Added support to search for reports of moons only.
anoff/teamview pull request #59
Opened 2023-01-23 22:03 UTC by kejith

2023-01-26 15:41 UTC, anoff requested changes
Thanks for the PR. Good idea to add that property.

But please keep the PR to the functional change not reformatting the files

2023-01-26 15:41 UTC, anoff commented on public/setup.user.js
> -// @connect      uni2.teamview.mietemieze.de
um... well... no :D 
guess we have to find a better way to configure this now that multiple people use it 👀

2023-01-26 15:41 UTC, anoff commented on userscript/features/galaxyview.js
> +function addUploadSection() {
please set your code formatter to `js standard` :)

2023-01-26 16:58 UTC, kejith commented on userscript/features/galaxyview.js
> +function addUploadSection() {
`please set your code formatter to js standard :)`
Will do

2023-01-26 16:59 UTC, kejith commented on public/setup.user.js
> -// @connect      uni2.teamview.mietemieze.de
We could build this file too, with a Setting to the API in the .env file? Could make it happen.

2023-01-26 17:31 UTC, kejith reviewed
So this should work right?

2023-01-27 13:47 UTC, anoff commented on userscript/ui/tabSearchReports.html
> +            <label for="is_moon">Mond: </label>
```suggestion
            <label for="is_moon">Moon: </label>
```

for now english. If you know how to add language support, let's talk :D

2023-01-29 11:09 UTC, anoff approved these changes
LGTM

Sorry for the delay 🌝

2023-01-29 11:09 UTC, merged