Take player Status into Consideration for Phalanxes in Range
anoff/teamview pull request #79
Opened 2023-02-26 21:23 UTC by kejith

![image](https://user-images.githubusercontent.com/5557752/221438053-88968f57-2efe-429a-b65a-aacca6ef08f4.png)
![image](https://user-images.githubusercontent.com/5557752/221438066-b83f4734-d661-4777-bd4e-ac76090390ae.png)

Player with Phalanx is:
Inactive -> Grey
Umode || Banned -> Blue
Active -> Red

2023-02-27 13:47 UTC, anoff commented on userscript/ui/tabStatus.js
> +      if (phalanx.galaxy === 4 && phalanx.system === 30) console.log({ phalanx, activity })
whaaaaat?

2023-02-27 13:47 UTC, anoff commented on userscript/ui/tabStatus.js
> +    if (system < 1 || system > 400) return 3
```suggestion
    if (system < 1 || system > 400) return ACTIVITY_ACTIVE
```

2023-02-27 13:50 UTC, anoff requested changes

2023-02-27 13:50 UTC, anoff commented on userscript/features/galaxyview.js
> +          <a style="color: ${color}; ${phalanx.isBanned ? 'text-decoration: line-through;' : ''}"
if you already decide to turn what can be done in 3 lines into a 23 line change, at least reuse the functions you created :P

2023-02-27 23:50 UTC, anoff commented on userscript/utils.js
> +    if (system < 1 || system > 400) return 'red'
seems random to just return `'red'` here.
Why not let the downstream function handle the edge cases (which it already does).

2023-02-27 23:50 UTC, anoff commented on userscript/utils.js
> +    if (system < 1 || system > 400) return false
please turn the `400` into a pseudo constant somewhere, too much magic numbers

2023-02-27 23:52 UTC, anoff commented on userscript/utils.js
> +    return this.data[system - 1]
If anywhere, doesn't this need the check for `1..400` bounds? :D

2023-02-27 23:55 UTC, anoff requested changes
Can you add some docstring pleaaaase?
It can be confusing to have methods with such similar names doing very different things `getActivity`, `getSystemActivity`, `getActivityColor`, `getSystemActivityColor`

2023-02-28 13:14 UTC, kejith commented on userscript/utils.js
> +    if (system < 1 || system > 400) return 'red'
Something went really wrong when this case happens and just to be safe we dont send a false negative we assume the system is in "danger" and color red. 

In Production no Galaxy should ever see this happening.

2023-03-06 20:50 UTC, anoff approved these changes
LGTM thanks :)

2023-03-06 20:54 UTC, merged